#!/bin/bash
c=$(xinput list | grep "$2" | grep "pointer" | grep -o id='[0-9]*' | awk '{print substr($1,4,3)}')
if [ "$1" = "off" ]; then
	xinput set-prop $c "Device Accel Profile" -1
elif [ "$1" = "on" ]; then
	xinput set-prop $c "Device Accel Profile" 0
fi
