#!/usr/bin/python3.4

import os
meingabe = "leer"
while(meingabe != "exit"):
	meingabe = input("Notiz [a]nlegen, Notizen [l]isten oder exit zum beenden: ")
	if(meingabe == "a"):
		nnotiz = input("Notizname: ")		
		nnotiz = "notiz_" + nnotiz
		if(os.path.exists(nnotiz)):
			print("Notiz existiert bereits!")
		else:			
			inotiz = input("Notiz: ")
			dnotiz = open(nnotiz,"w")
			dnotiz.write(inotiz)
	elif(meingabe == "l"):
		break
